apiVersion: v1
name: projectriff-riff
description: riff is for functions
keywords:
  - projectriff
  - riff
  - faas
home: https://projectriff.io
sources:
  - https://github.com/projectriff
icon: https://projectriff.io/images/riff.png
