---
## Use the '--set' flag for any of these properties to override defaults and/or tags settings
#cert-manager:
#  enabled: true
#keda:
#  enabled: false
#knative:
#  enabled: false
#kpack:
#  enabled: true
#riff:
#  build:
#    enabled: true
#  builders:
#    enabled: true
#  runtimes:
#    core:
#      enabled: false
#    knative:
#      enabled: false
#    streaming:
#      enabled: false
tags:
  build: true
  core-runtime: false
  knative-runtime: false
  streaming-runtime: false
