knative-build: https://storage.googleapis.com/knative-releases/build/previous/v0.7.0/build.yaml # --data-value dropKnativeImageCRD=true
knative-serving: https://storage.googleapis.com/knative-releases/serving/previous/v0.7.1/serving.yaml
